[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    WiFi
    WebServer
    ESPmDNS
    Wire

;board_build.filesystem = littlefs
;board_build.partitions = default_8MB.csv


;[env:adafruit_feather_esp32s3]
;platform = espressif32
;board = upesy_wroom
;framework = arduino
;
;monitor_speed = 115200
;upload_speed = 921600
;
;lib_deps =
;    WiFi
;    WebServer
;    ESPmDNS
;    Wire
;
;board_build.filesystem = littlefs
;;board_build.partitions = default_8MB.csv